from .cloth_common import *


SCENARIO_CONFIG = {
    "output": "cloth_cover_bunny",
    "enable_tearing": False,
    "asset": "cloth_and_static_bunny",
    "bunny_asset": "assets/bunny.obj",
    "scene_kind": "cloth_cover_bunny",
    "use_gravity": True,
    "gravity_scale": 0.1,
    "frames": 150,
    "fps": 30,
    "substeps": 40,
    "solver_iters": 200,
    "jacobi_relaxation": 0.45,
    "k_distance": 0.01,
    "k_volume": 0.9999,
    "k_bending": 0.03,
    "cloth_nx": 28,
    "cloth_ny": 28,
    "cloth_match_bunny_body_length": True,
    "cloth_body_length_axis": "x",
    "cloth_body_length_scale": 2.0,
    "cloth_body_depth_scale": 2.0,
    "cloth_width": 0.16,
    "cloth_height": 0.16,
    "cloth_checker_cells": 4,
    "cloth_drop_height": 0.20,
    "cloth_center_y_mode": "bunny_center_offset",
    "cloth_center_y_offset": 0.22,
    "collision_thickness": 0.01,
    "collision_cell_size": 0.018,
    "static_collision_k": 1.0,
    "static_collision_max_tris_per_cell": 256,
    "static_collision_neighbor_range": 1,
    "camera": {
        "bounds_mode": "first_frame",
        "target_mode": "bunny",
        "distance_scale": 3.6,
        "height_scale": 0.33,
        "side_scale": 0.34,
        "lens": 55,
        "bounds_padding": 1.2,
    },
}
