from .cloth_common import *


SCENARIO_CONFIG = {
    "output": "cloth_box_bunny",
    "enable_tearing": False,
    "asset": "cloth_box_deformable_bunny",
    "bunny_asset": "assets/bunny.obj",
    "scene_kind": "cloth_box_deformable_bunny",
    "use_gravity": True,
    "frames": 150,
    "fps": 30,
    "substeps": 10,
    "solver_iters": 120,
    "jacobi_relaxation": 0.55,
    "k_distance": 0.9999,
    "k_volume": 0.9999,
    "k_bending": 0.42,
    "cloth_nx": 30,
    "cloth_ny": 34,
    "cloth_width": 0.30,
    "cloth_checker_cells": 4,
    "cloth_height": 0.42,
    "cloth_drop_height": 0.28,
    "cloth_initial_pose": "u_over_bunny",
    "u_top_lift": 0.28,
    "u_back_offset": -0.07,
    "match_box_width_to_cloth": True,
    "box_half_extents": (0.085, 0.018, 0.04),
    "dynamic_box_mass": 8.0,
    "dynamic_box_initial_velocity": (0.0, 0.0, 0.0),
    "box_attachment_k": 1.0,
    "box_collision_k": 1.0,
    "box_floor_k": 1.0,
    "box_collision_margin": 0.002,
    "box_floor_restitution": 0.05,
    "collision_thickness": 0.003,
    "camera": {
        "bounds_mode": "all_frames",
        "target_mode": "bunny",
        "distance_scale": 4.0,
        "height_scale": 0.30,
        "side_scale": 0.38,
        "lens": 55,
        "bounds_padding": 1.35,
    },
}
