from .cloth_common import *


SCENARIO_CONFIG = {
    "output": "cloth_metal_drop",
    "enable_tearing": False,
    "asset": "cloth_procedural",
    "scene_kind": "cloth_metal_drop",
    "use_gravity": True,
    "frames": 150,
    "fps": 30,
    "substeps": 10,
    "solver_iters": 120,
    "jacobi_relaxation": 0.55,
    "k_distance": 0.9999,
    "k_volume": 0.9999,
    "k_bending": 0.45,
    "cloth_nx": 34,
    "cloth_ny": 38,
    "cloth_width": 0.34,
    "cloth_checker_cells": 4,
    "cloth_height": 0.48,
    "cloth_center": (0.0, 0.37, 0.0),
    "cloth_initial_pose": "u_drop",
    "u_top_y": 1.62,
    "u_back_y": 0.62,
    "u_low_y": 0.27,
    "u_back_offset": -0.16,
    "match_box_width_to_cloth": True,
    "box_half_extents": (0.09, 0.018, 0.04),
    "dynamic_box_mass": 8.0,
    "dynamic_box_initial_velocity": (0.0, 0.0, 0.0),
    "box_attachment_k": 1.0,
    "box_collision_k": 1.0,
    "box_floor_k": 1.0,
    "box_floor_restitution": 0.08,
    "collision_thickness": 0.003,
    "camera": {
        "bounds_mode": "all_frames",
        "target_mode": "bunny",
        "distance_scale": 4.0,
        "height_scale": 0.24,
        "side_scale": 0.30,
        "lens": 55,
        "bounds_padding": 1.25,
    },
}
