from .cloth_common import *


SCENARIO_CONFIG = {
    "output": "moving_bunny",
    "enable_tearing": False,
    "asset": "cloth_moving_bunny",
    "bunny_asset": "assets/bunny.obj",
    "scene_kind": "cloth_moving_bunny",
    "moving_static_bunny": True,
    "use_gravity": True,
    "gravity_scale": 0.35,
    "frames": 150,
    "fps": 30,
    "substeps": 40,
    "solver_iters": 160,
    "jacobi_relaxation": 0.45,
    "k_distance": 0.5,
    "k_volume": 0.9999,
    "k_bending": 0.9,
    "cloth_nx": 34,
    "cloth_ny": 42,
    "cloth_width": 0.30,
    "cloth_height": 0.35,
    "cloth_checker_cells": 4,
    "cloth_top_y": 0.43,
    "cloth_z": 0.0,
    "match_box_width_to_cloth": True,
    "top_box_half_extents": (0.15, 0.018, 0.035),
    "moving_bunny_start_offset": (0.0, 0.0, 0.0),
    "moving_bunny_velocity": (0.0, 0.0, 0.0),
    "moving_bunny_motion": "cosine_z",
    "moving_bunny_amplitude": 0.30,
    "moving_bunny_period": 5.0,
    "collision_thickness": 0.008,
    "collision_cell_size": 0.018,
    "static_collision_k": 1.0,
    "static_collision_max_tris_per_cell": 512,
    "static_collision_neighbor_range": 1,
    "camera": {
        "bounds_mode": "all_frames",
        "target_mode": "bunny",
        "distance_scale": 2.8,
        "height_scale": 0.28,
        "side_scale": 0.0,
        "orbit_degrees": -60.0,
        "lens": 55,
        "bounds_padding": 1.25,
    },
}
